[package]
name = "rust_snakegame"
version = "0.1.0"
edition = "2021"
authors = ["petervw <petervw1234@gmail.com>"]


[dependencies]
piston = "0.36.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.45.0"
piston2d-opengl_graphics = "0.52.0"
rand = "0.4"